name: Build Project

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '.github/**'
      - '.vscode/**'
      - 'docs/**'
      - mkdocs.yml
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - '.github/**'
      - '.vscode/**'
      - 'docs/**'
      - mkdocs.yml

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: dependencies
      run: sudo apt update && sudo apt -y install gcc-mingw-w64 make
    - name: make
      run: make
    - name: artifact
      uses: actions/upload-artifact@v4
      with:
        name: bridge
        path: build

  nightly:
    name: Upload Nightly Build to GitHub Releases
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Download All Builds
      uses: actions/download-artifact@v4

    - name: Update Nightly
      run: gh release upload nightly bridge/* -R ${{github.repository}} --clobber

    env:
      GH_TOKEN: ${{ github.token }}
