name: Build Project

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '.github/**'
      - '.vscode/**'
      - 'docs/**'
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - '.github/**'
      - '.vscode/**'
      - 'docs/**'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: dependencies
      run: sudo apt update && sudo apt -y install gcc-mingw-w64 make
    - name: make
      run: make
    - name: artifact
      uses: actions/upload-artifact@v4
      with:
        name: bridge
        path: build
